version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  # main-check:
  #   machine:
  #     image: ubuntu-2004:202101-01
  #     docker_layer_caching: false
  #   resource_class: arm.medium
  #   steps:
  #     - run: echo "Main branch detected!"
  build-and-push:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
    resource_class: arm.medium
    steps:
      - run:
          name: Setup Custom Environment Variables
          command: |
            echo "export REPO_NAME=$(printf '%s\n' \"${CIRCLE_PROJECT_REPONAME,,}\")" >> $BASH_ENV && \
            echo "export USER=$(printf '%s\n' \"${CIRCLE_PROJECT_USERNAME,,}\")" >> $BASH_ENV && \
            echo "export DOCKER_IMAGE_NAME=\"ghcr.io/\$USER/\$REPO_NAME\"" >> $BASH_ENV
      - checkout
      - docker/check:
          docker-username: CIRCLE_PROJECT_USERNAME
          registry: ghcr.io
      - run:
          name: Build and Push Containers
          command: |
            docker buildx create --use && ./build.sh --single
workflows:
  build:
    jobs:
      # - main-check:
      #     filters:
      #       branches:
      #         only: main
      - build-and-push:
          filters:
            tags: # see: https://circleci.com/blog/publishing-to-github-releases-via-circleci/
              only: /^\d+\.\d+\.\d+$/ #/(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
            branches:
              # only: main
              ignore: /.*/
          # requires:
          #   - main-check
