# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
# env:
#   REGISTRY: ghcr.io
#   DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#     - name: set image name to lower case
#       run: |
#         echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME,,}" >>${GITHUB_ENV}
#     - name: setup docker buildx
#       run: docker buildx create --use
#     - uses: actions/checkout@v3
#     - name: Log in to the Container registry
#       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     - name: Build the Docker image
#       run: ./build.sh
